"use strict";
let age = 25; // same as let age: any;
age = true;
console.log(age);
age = 'yoshi';
console.log(age);
age = { name: 'luigi', belt: 'black' };
console.log(age);
let mixed = [];
mixed.push(5);
mixed.push('mario');
mixed.push(false);
console.log(mixed);
